name: Codecov Backend Scan
on:
  push:
    branches:
      - main
    paths:
      - ".github/workflows/codecov.yml" # Replace it correctly with the path to your workflow file.
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  codecov:
    if: ( startsWith(github.head_ref, 'BE_') && github.event.pull_request.merged == false ) || ( github.event_name == 'push' )
    name: BE Codecov Analysis
    runs-on: ubuntu-latest
    timeout-minutes: 8
    defaults:
      run:
        working-directory: JsonDB
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v3
        with:
          path: ${{ github.workspace }}/frontend/node_modules
          key: ${{ runner.os }}-build-${{ hashFiles('**/package.json') }}
        env:
          cache-name: cache-node-modules

      - name: Install the dependencies
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: npm i

      - name: Run tests and generate coverage
        run: npm run coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
